spring.application.name=TourismSystem
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=TourismSystem;trustServerCertificate=true;encrypt=true;
spring.datasource.username=sa
spring.datasource.password=trungnghia282003
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html